### ISSUE TITLE
Sound Code is nonexistent or missing from the repository

### ISSUE THREAD

**Issue by Accusedbold** [luciusDXL/XL-Engine#18]
Both Gameloop.cpp and Services.cpp refer to a "sound/sound.h" - which is missing from the repository. I would also like to work on this project, and I request that these files be exposed so that I may add to this project. I am still a student - but I believe I have what it takes to work on a project like this. I have installed the Freetype and GL libraries, but I believe the only thing I need to compile this project is Sound/*. I am also new to this GitHub stuff so if I am doing something incorrectly - feel free to let me know. Thank you.

**Comment by 7oxicshadow** [comment]
See the following blog post:

http://xlengine.com/xl-engine-source-code/

"I will not be uploading all of the code until the Beta is published. The repository will be incomplete for now but that will be rectified for the release."

**Comment by luciusDXL** [comment]
This is a known issue, as described in the link above I am not accepting pull requests at this time. Once the Beta is published than all source code will be available so I am closing this issue.
