### ISSUE TITLE
The Website is Death , the Project still alive  ?

### ISSUE THREAD

**Issue by TP555** [luciusDXL/XL-Engine#25]
Hi

Is the Project DarkXL or another Games still alive ?

or gives a new Link for the Website now  ?

**Comment by ghost** [comment]
Is mindwerks same?
https://github.com/Mindwerks/XLEngine

more insight here:
https://github.com/Mindwerks/XLEngine/issues/40

**Comment by luciusDXL** [comment]
The project is begin retired. See the updated readme for more information.
